### PR TITLE
Client package split

### PR DESCRIPTION
**Pull request by Sollace**
This is the first commit from #15 with a fix for a broken mixins.json

Personally I don't like that skin servers have been dumped into a random "skins" package instead of keeping the old "net" name, but we can fix that later.

### CODE REVIEW

**Comment by killjoy1221** [comment]
If you provide mixin configs like that, it will make it harder to provide common mixins later

**Comment by Sollace** [comment]
I'm pretty sure you can specify more than one package for mixins. Change it when you actually do start providing common mixins.

**Comment by killjoy1221** [comment]
I renamed the net package in order to better reflect what it does. Net would be reserved for general network related classes, like java.net.URL. Not for things that just use it.

**Comment by killjoy1221** [comment]
I will defer to sponge for mixin best practices. 

https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/resources/mixins.forge.core.json

**Comment by Sollace** [comment]
I have no issue with it being renamed, I just don't think calling it "skins" is any more accurate. Skins to me implies that it's rendering related, and I would move things like the online/offline skin repositories into this folder, and the servers out.

**Comment by Sollace** [comment]
> 
> 
> I will defer to sponge for mixin best practices.
> 
> https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/resources/mixins.forge.core.json

Oh. Okay.

I didn't realise that was possible.

**Pull request merged**
